### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by spdustin** [growella/gravityforms-autocomplete-fields#6]
Has this project been abandoned, or have you found that it works "good enough" in its current state?

**Comment by stevegrunwell** [comment]
It hasn't necessarily been abandoned, but I was the one driving development and am no longer a part of Growella. I have permission from leadership to continue development on the @Growella open source projects, but my time for open-source work has been rather limited as of late.

The plan is to return to this repository eventually, but I can make no guarantees with regards to timing. If there are particular issues you're running into, please feel free to open issues (or pull requests 😉) on the repo.
